MODEL:
  NAME: 'resnet50'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: '/home/ubuntu/centroids-reid/models/verkada-neuron-resnet50.pt'
  KEEP_CAMID_CENTROIDS: True

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]

DATALOADER:
  NUM_INSTANCE: 4
  USE_RESAMPLING: True

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 40
  DISTANCE_FUNC: 'cosine'

TEST:
  IMS_PER_BATCH: 1
  ONLY_TEST: True
  FEAT_NORM: True

OUTPUT_DIR: './inference/logs'

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 3